### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by panno8M**
* `nimble test` to do whole tests
* `nim r tests/testproject` to run test-project
* `nimble compatibilityTest` to test project with Nim [2.0.0, 2.0.10, 2.2.0]
* Change to use the nimble standard testing system.
  * Tests that do not depend on godot can now coexist by placing them directly in the tests folder.

### CODE REVIEW

**Comment by panno8M** [comment]
I will not merge yet because I want an objective opinion.

@xix-xeaon Any thoughts?

**Comment by xix-xeaon** [comment]
I tested it and now it does compile the testproject. However, it doesn't actually run the tests (like those in `cases/geometrics.nim`). You can put in `check 1 == 2` and it doesn't fail.

I don't think it makes sense to have one test which tries to import everything. It takes a very long time to run and isn't modular. I would rather see it split up into multiple independent tests. If the files in _cases_ and _classes_ were all converted to the unittest and nimble standard that would improve the testing workflow a lot.

I did an experiment to get `cases/geometrics.nim` working (since it's already fully unittest):
- Moved it to the _tests_ folder and changed it's name to `test_geometrics.nim`.
- Added the file `config.nims` with the content `--path: "../src/"`.
- Removed the `when Assistance.checkEnv` block in `buildconf.nim`.
- In `buildconf.nim` made Extension.name equal to "test".
(I also removed `testproject.nim` temporarily.)

`nimble test` is now a nice workflow and the test can be run individually with `nim r`. Obviously it would have to be changed differently, that was just an experiment. But it seems that it can be achieved relatively easily.

There does need to be a testproject which actually builds the library, uses it as an extension for something basic, and runs Godot to see that it's working. But I think it needs to be designed as a unittest which checks for and detects if it actually works or not and closes Godot again. BTW, is there a need to have it test multiple versions normally? Maybe should be a switch, you could run as the last check before committing.

**Comment by panno8M** [comment]
> I tested it and now it does compile the testproject. However, it doesn't actually run the tests (like those in cases/geometrics.nim). You can put in check 1 == 2 and it doesn't fail.

Does that mean there is not even an output like [Suite] or [OK]?
It is functioning correctly here, so I will examine it in detail. Can you tell me your execution environment?

>I don't think it makes sense to have one test which tries to import everything. It takes a very long time to run and isn't modular. I would rather see it split up into multiple independent tests. If the files in cases and classes were all converted to the unittest and nimble standard that would improve the testing workflow a lot.

It is possible to compile them individually into dlls, but to make them work, one would have to create a .gdextension file for each and possibly add a node to the scene.

As a practical compromise, the current test project has a mix of things to check for behavior in the editor (e.g. property appearance) and things to check for behavior in the game, so they can be separated.

**Comment by xix-xeaon** [comment]
> Does that mean there is not even an output like [Suite] or [OK]?
Right, no output from the test. If it worked for you but not me that's certainly interesting. I don't think I have a special environment:
```
choosenim v0.8.9 (2024-10-02 12:54:38) [linux/amd64]
Nim Compiler Version 2.2.0 [Linux: amd64]
nimble v0.16.1 compiled at 2024-10-02 02:00:57
```

Your updates look good. I had to add `switch("path", "../src/")` to `tests/config.nims` (for the geometric test) but now I can run `nimble test` and it runs both the geometric test and the testproject test correctly and outputs [Suite] etc for both. All tests pass.

With the path (for the geometric test) included I think this can be merged. Any other potential refinements (like splitting it up more) can certainly be left for the future.

**Comment by panno8M** [comment]
Split testproject into testproject/runtime and testproject/editor.
In the normal nimble test, only testproject/runtime is compiled, while in the nimble compatibility test, both of them are compiled.

I would like you to run `nimble test` and `nimble compatibilityTest` in your environment. If it runs correctly, we will merge this PR.

**Comment by xix-xeaon** [comment]
There's a problem with the testproject, but I think I've figured it out.

> and the testproject test correctly and outputs [Suite] etc

That was actually not true under default conditions. Under default conditions the Godot testproject does not have `.godot` folder, which means it hasn't actually registered the existence of an extension, and missing other things too. I accidentally got it working before because I opened the project in the Godot editor. 

With your latest changes, again, the testproject compiles but has no test output because it fails to load the extension (there should be a test for this =P). After I open the project in Godot Editor it then works as expected.

**Comment by panno8M** [comment]
As to this, gdextwiz is updated. (When you run the `gdextwiz run` command, if the .godot folder does not exist, the editor will be launched instead.) Once you reinstall gdext, I believe it will be available.

Alright, other than this, there doesn't seem to be any other glaring problems.

**Pull request merged**
